---
title: "strings and factiors"
author: "Huili Zheng"
date: "10/23/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rvest)
library(p8105.datasets)
library(tidyverse)

```

## String vectors

```{r}
string_vec = c("my","name","is","Huili")

str_detect(string_vec, "m")
str_replace(string_vec,"Huili","huili")
```

```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
  )

str_detect(string_vec, "i think")
str_detect(string_vec, "^i think")  # begining of the line 
str_detect(string_vec, "i think$")  # end of the line 
```

```{r}
string_vec = c(
  "Y'all remember Pres. HW Bush?",
  "I saw a green bush",
  "BBQ and Bushwalking at Molonglo Gorge",
  "BUSH -- LIVE IN CONCERT!!"
  )

str_detect(string_vec,"[Bb]ush")
```

```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )

str_detect(string_vec, "^[0-9][a-zA-Z]")
```

```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )

str_detect(string_vec, "7.11")
```

```{r}
string_vec = c(
  'The CI is [2, 5]',
  ':-]',
  ':-[',
  'I found the answer on pages [6-7]'
  )
str_detect(string_vec, "\\[")
```


## Why factors are weird

```{r}
vec_sex = factor(c("male", "male", "female", "female"))
vec_sex
as.numeric(vec_sex)
as.numeric(fct_relevel(vec_sex, "male"))
```

## NSDUH

```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

table_marj = 
  read_html(nsduh_url) %>% 
  html_table() %>%
  first() %>%
  slice(-1)
```

let's clean up!

```{r}
data_marj = table_marj %>%
  select(-contains("P Value")) %>%
  pivot_longer(
    -State,
    names_to = "age_year",
    values_to = "percent") %>%
  separate(age_year,into = c("age","year"),"\\(") %>%
  mutate(
    year = str_replace(year,"\\)",""),
    percent = str_replace(percent, "[a-c]$",""),
    percent = as.numeric(percent)
  ) %>%
  filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))
```

do dataframe stuff

```{r}
data_marj %>%
  filter(age == "12-17") %>%
  mutate(
    State = fct_reorder(State,percent)
  ) %>%
  ggplot(aes(x = State, y = percent, color = year)) +
  geom_point()+
  theme(axis.text.x = element_text(angle = 90, hjust =1)) 
```


## Resturant inspections

```{r}
data("rest_inspec")

rest_inspec %>% slice(1:100) %>% view()
```

```{r}
rest_inspec %>%
  group_by(boro,grade) %>%
  summarize(count = n()) 
```

```{r}
rest_inspec %>%
  janitor::tabyl(boro,grade)
```

```{r}
rest_inspec = 
  rest_inspec %>%
  filter(
    str_detect(grade,"[ABC]"),
    !(boro == "Missing")
  ) %>% 
  mutate(boro = str_to_title(boro))
```

```{r}
rest_inspec %>%
  filter(str_detect(dba,"[Pp][Ii][Zz][Zz][Aa]")) %>%
  janitor::tabyl(boro,grade)
```


```{r}
rest_inspec %>%
  filter(str_detect(dba,"[Pp][Ii][Zz][Zz][Aa]")) %>%
  mutate(
    boro = fct_infreq(boro)
  ) %>%
  ggplot(aes(x = boro, fill = grade)) +
  geom_bar()
```

changing a label
```{r}
rest_inspec %>%
  filter(str_detect(dba,"[Pp][Ii][Zz][Zz][Aa]")) %>%
  mutate(
    boro = fct_infreq(boro),
    boro = fct_recode(boro,"The City" = "Manhattan")  # str_replace work tricky
  ) %>%
  ggplot(aes(x = boro, fill = grade)) +
  geom_bar()


```
